version: 2
jobs:
  build:
    docker:
      -image:node: 11.10.1

    working_directory: ^/repo


    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
        keys:
          - v1-dependencies-{{checksum "package.json"}}
          #fallback to using the latest cache if not exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules

          key: v1-dependencies-{{ checksum "package.json"}}

      # run test!

      - run: yarn test

      - run: yarn build


